import { StyleSheet } from 'react-native';
import { theme } from '../../../core/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.tokens.bg.canvas,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.tokens.bg.canvas,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#6b7280',
    },
    header: {
        backgroundColor: theme.tokens.bg.surface,
        borderBottomWidth: 1,
        borderBottomColor: theme.tokens.border.subtle,
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 12,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1f2937',
    },
    filterButton: {
        width: 36,
        height: 36,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    filterButtonActive: {
        backgroundColor: '#fff7ed',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        borderRadius: 12,
        paddingHorizontal: 12,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        height: 44,
        fontSize: 15,
        color: '#1f2937',
    },
    clearButton: {
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e5e7eb',
    },
    searchLoadingIndicator: {
        marginLeft: 4,
    },
    filterPanel: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    filterRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    filterLabel: {
        fontSize: 14,
        color: '#6b7280',
        marginRight: 12,
    },
    sortChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: theme.tokens.bg.subtle,
        marginRight: 8,
    },
    sortChipSelected: {
        backgroundColor: '#fff7ed',
    },
    sortChipText: {
        fontSize: 13,
        color: '#6b7280',
        textTransform: 'capitalize',
    },
    sortChipTextSelected: {
        color: '#FF6410',
        fontWeight: '500',
    },
    categoriesContainer: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingVertical: 12,
    },
    categoriesContent: {
        paddingHorizontal: 16,
        gap: 8,
    },
    categoryChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#f3f4f6',
        marginRight: 8,
    },
    categoryChipSelected: {
        backgroundColor: '#FF6410',
    },
    categoryChipText: {
        fontSize: 14,
        color: '#6b7280',
    },
    categoryChipTextSelected: {
        color: '#ffffff',
        fontWeight: '500',
    },
    roomList: {
        flex: 1,
    },
    roomListContent: {
        padding: 16,
        paddingBottom: 92,
    },
    group: {
        marginBottom: 24,
    },
    groupTitle: {
        fontSize: 13,
        fontWeight: '500',
        color: '#6b7280',
        marginBottom: 12,
        paddingHorizontal: 4,
    },
    roomCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 12,
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f3f4f6',
    },
    roomCardContent: {
        flexDirection: 'row',
        gap: 12,
    },
    emojiContainer: {
        position: 'relative',
    },
    roomEmoji: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#f3f4f6', // Softer default gray
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#FF6410',
        borderWidth: 2,
        borderColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    roomEmojiText: {
        fontSize: 20,
    },
    roomInfo: {
        flex: 1,
    },
    roomTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 2,
    },
    roomDescription: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 4,
        lineHeight: 16,
    },
    roomMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    metaText: {
        fontSize: 12,
        color: '#6b7280',
    },
    bottomMetaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 6,
    },
    badgesWrapper: {
        flexDirection: 'row',
        gap: 6,
        alignItems: 'center',
    },
    categoryBadge: {
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
        backgroundColor: '#f3e8ff',
    },
    categoryBadgeText: {
        fontSize: 10,
        color: '#7c3aed',
        fontWeight: '600',
    },
    timeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#f9fafb',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
    },
    timeText: {
        fontSize: 11,
        fontWeight: '500',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        elevation: 1,
    },
    newBadge: {
        backgroundColor: '#10b981',
    },
    activeBadge: {
        backgroundColor: '#f43f5e',
    },
    scrollTopButtonContainer: {
        position: 'absolute',
        top: 190, // Positioned closer to categories (was 200)
        left: 0,
        right: 0,
        alignItems: 'center',
        zIndex: 50,
    },
    scrollTopButtonInList: {
        position: 'absolute',
        top: 4, // Just below the top of the list container
        left: 0,
        right: 0,
        alignItems: 'center',
        zIndex: 50,
    },
    scrollTopButton: {
        backgroundColor: 'rgba(243, 244, 246, 0.8)', // Semi-transparent pale gray
        width: 36, // Small circle
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(229, 231, 235, 0.8)', // Semi-transparent border
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    statusBadgeText: {
        color: '#ffffff',
        fontSize: 7,
        fontWeight: '700',
    },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 2,
    },
    topRightMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderRadius: 28,
        padding: 20,
        width: '100%',
        maxWidth: 320,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 15,
        elevation: 8,
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 20,
    },
    modalEmojiContainer: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: '#fff7ed',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    modalEmoji: {
        fontSize: 28,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        textAlign: 'center',
        marginBottom: 6,
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#6b7280',
        textAlign: 'center',
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 14,
        backgroundColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#64748b',
    },
    confirmButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 14,
        backgroundColor: '#FF6410',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#FF6410',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    confirmButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#ffffff',
    },
    statusBadgesContainer: {
        position: 'absolute',
        bottom: -6,
        left: -4,
        right: -4,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 4,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    emptyIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#fff7ed',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    emptyIconSearch: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 8,
    },
    emptySubtitle: {
        fontSize: 14,
        color: '#6b7280',
        textAlign: 'center',
        marginBottom: 24,
    },
    emptyButton: {
        paddingHorizontal: 24,
        paddingVertical: 12,
        backgroundColor: '#FF6410',
        borderRadius: 16,
    },
    emptyButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
    },
    emptyButtonSecondary: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#f3f4f6',
        borderRadius: 8,
        marginBottom: 16,
    },
    emptyButtonSecondaryText: {
        fontSize: 14,
        color: '#6b7280',
    },
    footer: {
        textAlign: 'center',
        fontSize: 13,
        color: '#6b7280',
        paddingVertical: 16,
    },
    loadingMoreContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 20,
        gap: 12,
    },
    loadingMoreText: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
    },
    endOfListContainer: {
        paddingVertical: 20,
        alignItems: 'center',
    },
    endOfListText: {
        fontSize: 13,
        color: '#16a34a',
        fontWeight: '600',
    },
});
